stages:
  load:
    cmd: python get_product_success.py '' ''
    deps: 
    - get_product_success.py
    - ''
    - ''
    outs:
    - combined_df
    - review_df
    - meta_filename
    - review_filename
  supervised_ml:
    cmd: python run_supervised.py combined_df 
    deps:
      - sun_supervised.py
      - combined_df
    outs:
      - supervised_model.pkl
      - visuals.jpg
  product_summary:
      cmd: python product_summary.py combined_df review_df
      deps:
        - product_summary.py
        - combined_df
        - review_df
      outs:
        - combined_df #should Name change?
  clustering_reviews:
    cmd: python clustering_reviews.py combined_df review_df
    deps:
      - clustering_reviews.py  
      - combined_df
      - review_df
    outs:
      - clustering_reviews_model.pkl
      - clusters.jpg
      - review_df # with potential fake news removed?
  clustering_product_reviews:
    cmd: python clustering_product_reviews.py combined_df review_df
    deps:
      - clustering_product_reviews.py  
      - combined_df
      - review_df
    outs:
      - clustering_product_reviews_model.pkl
      - clusters.jpg
      - review_df # with potential fake news removed?
  

