stages:
  load_data:
    cmd: python load_data.py
    deps:
    - load_data.py
    params:
    - load_data.cat_meta_url
    - load_data.cat_review_url
    outs:
    - data/prepared
  preprocess_products:
    cmd: python preprocess_products.py data/prepared
    deps:
    - preprocess_products.py
    - data/prepared
    params:
    - preprocess_products
    outs:
    - data/products
  preprocess_reviews:
    cmd: python preprocess_reviews.py data/prepared
    deps:
    - preprocess_reviews.py
    - data/prepared
    outs:
    - data/reviews
  success_metrics:
    cmd: python create_success_metrics.py  
    deps:
    - create_success_metrics.py
    - data/products
    - data/reviews
    - data/fake/fake_free_data
    params:
    - success_metrics.cutoff
    - success_metrics.fake_free_data
    outs:
    - data/metrics
  supervised_model:
    cmd: python model_supervised.py data/metrics
    deps:
    - model_supervised.py
    - data/metrics
    params:
    - supervised_model.model_type
    - supervised_model.params
    - supervised_model.scale
    - supervised_model.oversample
    - supervised_model.gscv
    - supervised_model.param_dict
    - supervised_model.n_jobs
    - supervised_model.return_train_score
    - supervised_model.split
    - supervised_model.pca
    - supervised_model.pca_n_components
    - supervised_model.cluster_features
    - supervised_model.best_k
    - supervised_model.ada_base_model
    - supervised_model.ada_base_iter
    - supervised_model.ada_max_depth
    - supervised_model.n_jobs
    - supervised_model.return_train_score
    - tfidf_product_success.min_df
    - tfidf_product_success.max_df
    outs:
    - model/product_success/
  evaluate_supervised:
    cmd: python evaluate_supervised.py prdct_supervised_report.json
    deps:
    - evaluate_supervised.py
    - model/product_success/
    params:
    - evaluate_supervised.clf
    - evaluate_supervised.X_test
    - evaluate_supervised.X_train
    - evaluate_supervised.X_val
    - evaluate_supervised.y_test
    - evaluate_supervised.y_train
    - evaluate_supervised.y_val
    - evaluate_supervised.f1_avg
    metrics:
    - prdct_supervised_report.json:
        cache: false
  prepare_fake_labeled_model:
    cmd: python load_prepare_fake_labeled_data.py
    deps:
    - data/fake/labeled_data/amazon_reviews_labeled.txt
    - load_prepare_fake_labeled_data.py
    params:
    - load_prepare_fake.features
    - load_prepare_fake.word2vec_model_name
    - fake_review_labeled_file_path
    outs:
    - data/fake/training/labeled_processed.pkl
  fd_supervised_model:
    cmd: python fake_detection_model.py data/fake/training/
    deps:
    - data/fake/training/
    - fake_detection_model.py
    params:
    - fd_supervised_model.model_type
    - fd_supervised_model.scale
    - fd_supervised_model.oversample
    - fd_supervised_model.gscv
    - fd_supervised_model.tfidf
    - fd_supervised_model.pca
    - fd_supervised_model.pca_n_components
    - fd_supervised_model.ada_base_model
    - fd_supervised_model.ada_base_iter
    - fd_supervised_model.param_dict
    - fd_supervised_model.ada_max_depth
    - fd_supervised_model.n_jobs
    - fd_supervised_model.return_train_score
    - fd_supervised_model.split
    - fd_supervised_model.params
    - tfidf_fake_review.min_df
    - tfidf_fake_review.max_df
    outs:
    - model/fake/
  fd_evaluate_supervised:
    cmd: python fd_evaluate_supervised.py fd_supervised_report.json
    deps:
    - fd_evaluate_supervised.py
    - model/fake/
    params:
    - fd_evaluate_supervised.f1_avg
    metrics:
    - fd_supervised_report.json:
        cache: false
  predicting_fake_reviews:
    cmd: python fd_test_model.py
    deps:
    - fd_test_model.py
    - data/prepared/
    - model/fake
    params:
    - fd_test_stage
    outs:
    - data/fake/fake_free_data/
  clustering_reviews:
    cmd: python clustering_reviews.py
    deps: 
    - clustering_reviews.py
    - data/prepared/reviews.pkl
    - data/reviews/reviews.pkl
    - data/fake/fake_free_data/fake_free_reviews.npy
    params:
    - clustering_model 
