stages:
  load_data:
    cmd: python load_data.py http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles2/meta_Appliances.json.gz
      http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Appliances.json.gz
    deps:
    - http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Appliances.json.gz
    - http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles2/meta_Appliances.json.gz
    - load_data.py
    outs:
    - dvc_data
