stages:
  load_data:
    cmd: python load_data.py
    deps:
    - load_data.py
    outs:
    - data/prepared
  preprocess_products:
    cmd: python preprocess_products.py data/prepared
    deps:
    - preprocess_products.py
    - data/prepared
    params:
    - preprocess_products
    outs:
    - data/products
  preprocess_reviews:
    cmd: python preprocess_reviews.py data/prepared
    deps:
    - preprocess_reviews.py
    - data/prepared
    outs:
    - data/reviews
  success_metrics:
    cmd: python create_success_metrics.py data/products data/reviews
    deps:
    - create_success_metrics.py
    - data/products
    - data/reviews
    params:
    - success_metrics.cutoff
    outs:
    - data/metrics
  supervised_model:
    cmd: python model_supervised.py data/metrics
    deps:
    - model_supervised.py
    - data/metrics
    params:
    - supervised_model.model_type
    - supervised_model.params
    - supervised_model.scale
    - supervised_model.oversample
    - supervised_model.gscv
    - supervised_model.param_dict
    - supervised_model.n_jobs
    - supervised_model.return_train_score
    - supervised_model.split
    outs:
    - model/product_success/
    
  evaluate_supervised:
    cmd: python evaluate_supervised.py prdct_supervised_report.json
    deps:
    - evaluate_supervised.py
    - model/product_success/
    metrics:
    - prdct_supervised_report.json:
        cache: false


  prepare_fake_labeled_model:
    cmd: python load_prepare_fake_labeled_data.py
    deps:
    - data/fake/labeled_data/amazon_reviews_labeled.txt
    - load_prepare_fake_labeled_data.py
    outs:
    - data/fake/training/labeled_processed.pkl
  fd_supervised_model:
    cmd: python fake_detection_model.py data/fake/training/
    deps:
    - data\fake\training\
    - fake_detection_model.py
    outs:
    - model\fake\
  fd_evaluate_supervised:
    cmd: python fd_evaluate_supervised.py fd_supervised_report.json
    deps:
    - fd_evaluate_supervised.py
    - model/fake/
    metrics:
    - fd_supervised_report.json:
        cache: false
