load_data:
    cat_meta_url: http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles2/meta_Appliances.json.gz
    cat_review_url: http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Appliances.json.gz
preprocess_products:
    word2vec_features: True
    handpicked_features: True
    word2vec_model_name: 'glove-wiki-gigaword-300'
    pca: True
    tfidf: True
    occurrence_threshold: 500 #threshold of occurrence of a category to be extracted by the vectorizer 
    
success_metrics:
    cutoff: 2

# base_model/base_iter is only for AdaBoostClassifier

supervised_model:
    model_type: SVC
    scale: True
    oversample: False
    gscv: False
    ada_base_model: DecisionTreeClassifier
    ada_base_iter: [3,9,15]
    param_dict: {
        C : [0.1,1, 10, 100],
        gamma : [1,0.1,0.01,0.001],
        kernel : ['rbf', 'poly', 'sigmoid'],
        random_state : [42]
    } 
    ada_max_depth : 3 #for non-grid search AdaBoost base model
    n_jobs: 1
    return_train_score: False
    split: 0.8
    params: 
        random_state : 42
        C : 1
        gamma : 1
        kernel : 'rbf' 

evaluate_supervised:
    clf: model/model.pkl
    X_test: model/X_test.npy
    X_train: model/X_train.npy
    X_val: model/X_val.npy
    y_test: model/y_test.npy
    y_train: model/y_train.npy
    y_val: model/y_val.npy
    f1_avg: "weighted"

run_pca:
    n_components: 25

tfidf:
    min_df: 0.05
    max_df: 0.7

    
    
