load_data:
    cat_meta_url: http://deepyeti.ucsd.edu/jianmo/amazon/metaFiles2/meta_Appliances.json.gz
    cat_review_url: http://deepyeti.ucsd.edu/jianmo/amazon/categoryFiles/Appliances.json.gz
preprocess_products:
    word2vec_features: True
    handpicked_features: True
    word2vec_model_name: 'glove-wiki-gigaword-300'
    occurrence_threshold: 500 #threshold of occurrence of a category to be extracted by the vectorizer 
    
success_metrics:
    cutoff: 2
    fake_free_data: False #to use the raw dataset or the dataset of fake_free_dataset from the supervised model

random_state: 42
# base_model/base_iter is only for AdaBoostClassifier

supervised_model:
    model_type: GradientBoostingClassifier
    scale: True
    oversample: False
    gscv: False
    tfidf: True
    pca: True
    pca_n_components : 55
    cluster_features : True
    best_k : 1000           # put 'search' if you want to iterate takes awhile otherwise put in best_k for faster run
    ada_base_model: DecisionTreeClassifier
    ada_base_iter: [1,3,5]
    param_dict: {
        learning_rate : [0.005,0.01,0.015],
        subsample : [0.5,0.8],
        n_estimators : [1200,1300,1400],
        max_depth : [8]
        }

    ada_max_depth : 3   #for non-grid search AdaBoost base model
    n_jobs: -1
    split: 0.8
    params:
        random_state : 42
        C : 0.000954095476
        penalty : 'l2'
        solver : 'saga'


evaluate_supervised:
    clf: model/product_success/model.pkl
    X_test: model/product_success/X_test.npy
    X_train: model/product_success/X_train.npy
    X_val: model/product_success/X_val.npy
    y_test: model/product_success/y_test.npy
    y_train: model/product_success/y_train.npy
    y_val: model/product_success/y_val.npy
    f1_avg: "weighted"

fd_evaluate_supervised:
    f1_avg: "weighted"

tfidf_product_success:
    min_df: 0.05
    max_df: 0.7

tfidf_fake_review:
    min_df: 0.05
    max_df: 0.7

fake_review_labeled_file_path: data/fake/labeled_data/amazon_reviews_labeled.txt
load_prepare_fake:
    features:
        word2vec_features: True
        handpicked_features: True
    word2vec_model_name: 'glove-wiki-gigaword-300' 

fd_supervised_model:
    model_type: SVC
    scale: True
    oversample: False
    gscv: True
    tfidf: True
    pca: True
    pca_n_components : 100
    ada_base_model: DecisionTreeClassifier
    ada_base_iter: [2,8,10]
    param_dict: {
        C : [10,15,20,25,30,35,40],
        kernel : ['linear'],
        random_state : [42],
        
    } 
    
    #  {
    #     C : [1.00000000e-04, 1.45634848e-04, 2.12095089e-04, 3.08884360e-04,
    #     4.49843267e-04, 6.55128557e-04, 9.54095476e-04, 1.38949549e-03,
    #     2.02358965e-03, 2.94705170e-03, 4.29193426e-03, 6.25055193e-03,
    #     9.10298178e-03, 1.32571137e-02, 1.93069773e-02, 2.81176870e-02,
    #     4.09491506e-02, 5.96362332e-02, 8.68511374e-02, 1.26485522e-01,
    #     1.84206997e-01, 2.68269580e-01, 3.90693994e-01, 5.68986603e-01,
    #     8.28642773e-01, 1.20679264e+00, 1.75751062e+00, 2.55954792e+00,
    #     3.72759372e+00, 5.42867544e+00, 7.90604321e+00, 1.15139540e+01,
    #     1.67683294e+01, 2.44205309e+01, 3.55648031e+01, 5.17947468e+01,
    #     7.54312006e+01, 1.09854114e+02, 1.59985872e+02, 2.32995181e+02,
    #     3.39322177e+02, 4.94171336e+02, 7.19685673e+02, 1.04811313e+03,
    #     1.52641797e+03, 2.22299648e+03, 3.23745754e+03, 4.71486636e+03,
    #     6.86648845e+03, 1.00000000e+04],
    #     penalty : ['l1', 'l2'],
    #     random_state : [42],
    #     solver : ['saga'],
        
    # } 
    ada_max_depth : 3 #for non-grid search AdaBoost base model
    n_jobs: -1
    split: 0.8
    params: 
        random_state : 42
        C : 100
         
fd_test_stage:
    tfidf_path: model/fake/tfidf_fitted_model.pkl
    pca_fitted_path: model/fake/pca_fitted_model.pkl
    scaler_fitted_path: model/fake/scaler_fitted_model.pkl
    model_fitted: model/fake/model.pkl
clustering_model:
    data_source: fake_free  #options: raw, preprocessed, fake_free
    model_type: KMeans #options: KMeans, MiniBatchKMeans, DBSCAN
    params: None 
    raw_data_params:
        tfidf_params:
            min_df: 0.05,
            max_df: 0.7, 
            stop_words: "english"
            ngram_range: (1,2)
        scale: True
        reducer:
            name: PCA  #options: LSA, NMF (PCA is default)
            n_components: 50
   
    
