preprocess_products:
    word2vec_features: True
    handpicked_features: True
    word2vec_model_name: 'glove-wiki-gigaword-300'
    pca: True
    tfidf: True
    occurrence_threshold: 500 #threshold of occurrence of a category to be extracted by the vectorizer 
    
success_metrics:
    cutoff: 2

# base_model/base_iter is only for AdaBoostClassifier

supervised_model:
    model_type: AdaBoostClassifier
    scale: False
    oversample: False
    gscv: True
    ada_base_model: DecisionTreeClassifier
    ada_base_iter: [3,9,15]
    param_dict: {
        learning_rate : [0.005,1],
        n_estimators : [100,3000],
        random_state : [42]
    } 

    n_jobs: 1
    return_train_score: False
    split: 0.8
    params: 
        random_state : 42
        max_iter : 5000
        solver: saga
        class_weight : balanced 

evaluate_supervised:
    clf: model/model.pkl
    X_test: model/X_test.npy
    X_train: model/X_train.npy
    X_val: model/X_val.npy
    y_test: model/y_test.npy
    y_train: model/y_train.npy
    y_val: model/y_val.npy
    f1_avg: "weighted"

run_pca:
    n_components: 25

tfidf:
    min_df: 0.05
    max_df: 0.7
    
    
    
