preprocess_products:
    word2vec_features: True
    handpicked_features: True
    word2vec_model_name: 'glove-wiki-gigaword-300'
    pca: True
    tfidf: True
    occurrence_threshold: 500 #threshold of occurrence of a category to be extracted by the vectorizer 
    
success_metrics:
    cutoff: 10

supervised_model:
    model_type: LogisticRegression
    scale: True
    oversample: False
    gscv: False
    param_dict: {
        "bas_estimator": [DecisionTreeClassifier(max_depth=5), DecisionTreeClassifier(max_depth=8), DecisionTreeClassifier(max_depth=12)],
        "learning_rate": [0.005, 0.01, 1],
        "n_estimators": [100, 2000, 3000],
        "random_sate" : [42] 
    }
    n_jobs: 1
    return_train_score: False
    split: 0.6
    params: 
        random_state : 42
        max_iter : 5000
        solver: saga
        class_weight : balanced 

evaluate_supervised:
    clf: model/model.sav
    X_test: model/X_test.npy
    X_train: model/X_train.npy
    X_val: model/X_val.npy
    y_test: model/y_test.npy
    y_train: model/y_train.npy
    y_val: model/y_val.npy
    f1_avg: "weighted"

run_pca:
    n_components: 25

tfidf:
    min_df: 0.05
    max_df: 0.7
    
    
    
