preprocess_products:
    word2vec_features: True
    handpicked_features: True
    word2vec_model_name: 'glove-wiki-gigaword-300'
    pca: True
    
success_metrics:
    cutoff: 2

supervised_model:
    model_type: GradientBoostingClassifier
    scale: False
    oversample: False
    gscv: True
    param_dict: 
        max_depth : [5,10,12]
        learning_rate : [0.005,0.01]
        n_estimators : [2000,3000]
        random_state : [42] 
    n_jobs: 1
    return_train_score: False
    split: 0.8
    params: 
        random_state : 42
        max_iter : 5000
        solver: saga
        class_weight : balanced 

evaluate_supervised:
    clf: model/model.sav
    X_test: model/X_test.npy
    X_train: model/X_train.npy
    X_val: model/X_val.npy
    y_test: model/y_test.npy
    y_train: model/y_train.npy
    y_val: model/y_val.npy
    f1_avg: "weighted"

run_pca:
    n_components: 25
    
    
    
