preprocess_products:
    word2vec_features: True
    handpicked_features: True
    word2vec_model_name: 'glove-wiki-gigaword-300'
    pca: True
    
success_metrics:
    cutoff: 10

supervised_model:
    model_type: LogisticRegression
    params: 
        random_state : 42
        max_iter : 5000
        solver: saga
        class_weight : balanced 
    scale: True
    oversample: False
    gscv: False
    param_dict: None
    n_jobs: 1
    return_train_score: False
    split: 0.6

run_pca:
    n_components: 25
    
    
    
